environment:
  DYNAMODB_ENDPOINT_URL: ${env:DYNAMODB_ENDPOINT_URL,'http://localhost:5000'}
  PLATFORM_HIGH_LEVEL_REGION: '${self:custom.highLevelRegion}'
  SERVICE_ID: '${self:custom.serviceId}'
  STAGE: '${self:provider.stage}'
